/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as RegisterCompanyRouteImport } from './routes/register.company'
import { Route as RegisterCandidateRouteImport } from './routes/register.candidate'
import { Route as AppVideosRouteImport } from './routes/app.videos'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppLeaderboardRouteImport } from './routes/app.leaderboard'
import { Route as AppJobsRouteImport } from './routes/app.jobs'
import { Route as AppInterviewRouteImport } from './routes/app.interview'
import { Route as AppInternshipsRouteImport } from './routes/app.internships'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCompanyRouteImport } from './routes/app.company'
import { Route as AppChallengesRouteImport } from './routes/app.challenges'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppCompanyIndexRouteImport } from './routes/app.company.index'
import { Route as AppCompanyTalentRouteImport } from './routes/app.company.talent'
import { Route as AppCompanyEvaluateRouteImport } from './routes/app.company.evaluate'
import { Route as AppCompanyCreateChallengeRouteImport } from './routes/app.company.create-challenge'
import { Route as AppChallengesSubmitRouteImport } from './routes/app.challenges.submit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterCompanyRoute = RegisterCompanyRouteImport.update({
  id: '/register/company',
  path: '/register/company',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterCandidateRoute = RegisterCandidateRouteImport.update({
  id: '/register/candidate',
  path: '/register/candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVideosRoute = AppVideosRouteImport.update({
  id: '/app/videos',
  path: '/app/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/app/tasks',
  path: '/app/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLeaderboardRoute = AppLeaderboardRouteImport.update({
  id: '/app/leaderboard',
  path: '/app/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/app/jobs',
  path: '/app/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInterviewRoute = AppInterviewRouteImport.update({
  id: '/app/interview',
  path: '/app/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInternshipsRoute = AppInternshipsRouteImport.update({
  id: '/app/internships',
  path: '/app/internships',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompanyRoute = AppCompanyRouteImport.update({
  id: '/app/company',
  path: '/app/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChallengesRoute = AppChallengesRouteImport.update({
  id: '/app/challenges',
  path: '/app/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompanyIndexRoute = AppCompanyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCompanyRoute,
} as any)
const AppCompanyTalentRoute = AppCompanyTalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => AppCompanyRoute,
} as any)
const AppCompanyEvaluateRoute = AppCompanyEvaluateRouteImport.update({
  id: '/evaluate',
  path: '/evaluate',
  getParentRoute: () => AppCompanyRoute,
} as any)
const AppCompanyCreateChallengeRoute =
  AppCompanyCreateChallengeRouteImport.update({
    id: '/create-challenge',
    path: '/create-challenge',
    getParentRoute: () => AppCompanyRoute,
  } as any)
const AppChallengesSubmitRoute = AppChallengesSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => AppChallengesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/challenges': typeof AppChallengesRouteWithChildren
  '/app/company': typeof AppCompanyRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/internships': typeof AppInternshipsRoute
  '/app/interview': typeof AppInterviewRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/videos': typeof AppVideosRoute
  '/register/candidate': typeof RegisterCandidateRoute
  '/register/company': typeof RegisterCompanyRoute
  '/app/': typeof AppIndexRoute
  '/app/challenges/submit': typeof AppChallengesSubmitRoute
  '/app/company/create-challenge': typeof AppCompanyCreateChallengeRoute
  '/app/company/evaluate': typeof AppCompanyEvaluateRoute
  '/app/company/talent': typeof AppCompanyTalentRoute
  '/app/company/': typeof AppCompanyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/challenges': typeof AppChallengesRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/internships': typeof AppInternshipsRoute
  '/app/interview': typeof AppInterviewRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/videos': typeof AppVideosRoute
  '/register/candidate': typeof RegisterCandidateRoute
  '/register/company': typeof RegisterCompanyRoute
  '/app': typeof AppIndexRoute
  '/app/challenges/submit': typeof AppChallengesSubmitRoute
  '/app/company/create-challenge': typeof AppCompanyCreateChallengeRoute
  '/app/company/evaluate': typeof AppCompanyEvaluateRoute
  '/app/company/talent': typeof AppCompanyTalentRoute
  '/app/company': typeof AppCompanyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/challenges': typeof AppChallengesRouteWithChildren
  '/app/company': typeof AppCompanyRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/internships': typeof AppInternshipsRoute
  '/app/interview': typeof AppInterviewRoute
  '/app/jobs': typeof AppJobsRoute
  '/app/leaderboard': typeof AppLeaderboardRoute
  '/app/profile': typeof AppProfileRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/videos': typeof AppVideosRoute
  '/register/candidate': typeof RegisterCandidateRoute
  '/register/company': typeof RegisterCompanyRoute
  '/app/': typeof AppIndexRoute
  '/app/challenges/submit': typeof AppChallengesSubmitRoute
  '/app/company/create-challenge': typeof AppCompanyCreateChallengeRoute
  '/app/company/evaluate': typeof AppCompanyEvaluateRoute
  '/app/company/talent': typeof AppCompanyTalentRoute
  '/app/company/': typeof AppCompanyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/app/admin'
    | '/app/challenges'
    | '/app/company'
    | '/app/dashboard'
    | '/app/internships'
    | '/app/interview'
    | '/app/jobs'
    | '/app/leaderboard'
    | '/app/profile'
    | '/app/tasks'
    | '/app/videos'
    | '/register/candidate'
    | '/register/company'
    | '/app/'
    | '/app/challenges/submit'
    | '/app/company/create-challenge'
    | '/app/company/evaluate'
    | '/app/company/talent'
    | '/app/company/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/app/admin'
    | '/app/challenges'
    | '/app/dashboard'
    | '/app/internships'
    | '/app/interview'
    | '/app/jobs'
    | '/app/leaderboard'
    | '/app/profile'
    | '/app/tasks'
    | '/app/videos'
    | '/register/candidate'
    | '/register/company'
    | '/app'
    | '/app/challenges/submit'
    | '/app/company/create-challenge'
    | '/app/company/evaluate'
    | '/app/company/talent'
    | '/app/company'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/app/admin'
    | '/app/challenges'
    | '/app/company'
    | '/app/dashboard'
    | '/app/internships'
    | '/app/interview'
    | '/app/jobs'
    | '/app/leaderboard'
    | '/app/profile'
    | '/app/tasks'
    | '/app/videos'
    | '/register/candidate'
    | '/register/company'
    | '/app/'
    | '/app/challenges/submit'
    | '/app/company/create-challenge'
    | '/app/company/evaluate'
    | '/app/company/talent'
    | '/app/company/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  AppAdminRoute: typeof AppAdminRoute
  AppChallengesRoute: typeof AppChallengesRouteWithChildren
  AppCompanyRoute: typeof AppCompanyRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppInternshipsRoute: typeof AppInternshipsRoute
  AppInterviewRoute: typeof AppInterviewRoute
  AppJobsRoute: typeof AppJobsRoute
  AppLeaderboardRoute: typeof AppLeaderboardRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTasksRoute: typeof AppTasksRoute
  AppVideosRoute: typeof AppVideosRoute
  RegisterCandidateRoute: typeof RegisterCandidateRoute
  RegisterCompanyRoute: typeof RegisterCompanyRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/company': {
      id: '/register/company'
      path: '/register/company'
      fullPath: '/register/company'
      preLoaderRoute: typeof RegisterCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/candidate': {
      id: '/register/candidate'
      path: '/register/candidate'
      fullPath: '/register/candidate'
      preLoaderRoute: typeof RegisterCandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/videos': {
      id: '/app/videos'
      path: '/app/videos'
      fullPath: '/app/videos'
      preLoaderRoute: typeof AppVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/app/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/leaderboard': {
      id: '/app/leaderboard'
      path: '/app/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AppLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/jobs': {
      id: '/app/jobs'
      path: '/app/jobs'
      fullPath: '/app/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/interview': {
      id: '/app/interview'
      path: '/app/interview'
      fullPath: '/app/interview'
      preLoaderRoute: typeof AppInterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/internships': {
      id: '/app/internships'
      path: '/app/internships'
      fullPath: '/app/internships'
      preLoaderRoute: typeof AppInternshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/company': {
      id: '/app/company'
      path: '/app/company'
      fullPath: '/app/company'
      preLoaderRoute: typeof AppCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/challenges': {
      id: '/app/challenges'
      path: '/app/challenges'
      fullPath: '/app/challenges'
      preLoaderRoute: typeof AppChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/company/': {
      id: '/app/company/'
      path: '/'
      fullPath: '/app/company/'
      preLoaderRoute: typeof AppCompanyIndexRouteImport
      parentRoute: typeof AppCompanyRoute
    }
    '/app/company/talent': {
      id: '/app/company/talent'
      path: '/talent'
      fullPath: '/app/company/talent'
      preLoaderRoute: typeof AppCompanyTalentRouteImport
      parentRoute: typeof AppCompanyRoute
    }
    '/app/company/evaluate': {
      id: '/app/company/evaluate'
      path: '/evaluate'
      fullPath: '/app/company/evaluate'
      preLoaderRoute: typeof AppCompanyEvaluateRouteImport
      parentRoute: typeof AppCompanyRoute
    }
    '/app/company/create-challenge': {
      id: '/app/company/create-challenge'
      path: '/create-challenge'
      fullPath: '/app/company/create-challenge'
      preLoaderRoute: typeof AppCompanyCreateChallengeRouteImport
      parentRoute: typeof AppCompanyRoute
    }
    '/app/challenges/submit': {
      id: '/app/challenges/submit'
      path: '/submit'
      fullPath: '/app/challenges/submit'
      preLoaderRoute: typeof AppChallengesSubmitRouteImport
      parentRoute: typeof AppChallengesRoute
    }
  }
}

interface AppChallengesRouteChildren {
  AppChallengesSubmitRoute: typeof AppChallengesSubmitRoute
}

const AppChallengesRouteChildren: AppChallengesRouteChildren = {
  AppChallengesSubmitRoute: AppChallengesSubmitRoute,
}

const AppChallengesRouteWithChildren = AppChallengesRoute._addFileChildren(
  AppChallengesRouteChildren,
)

interface AppCompanyRouteChildren {
  AppCompanyCreateChallengeRoute: typeof AppCompanyCreateChallengeRoute
  AppCompanyEvaluateRoute: typeof AppCompanyEvaluateRoute
  AppCompanyTalentRoute: typeof AppCompanyTalentRoute
  AppCompanyIndexRoute: typeof AppCompanyIndexRoute
}

const AppCompanyRouteChildren: AppCompanyRouteChildren = {
  AppCompanyCreateChallengeRoute: AppCompanyCreateChallengeRoute,
  AppCompanyEvaluateRoute: AppCompanyEvaluateRoute,
  AppCompanyTalentRoute: AppCompanyTalentRoute,
  AppCompanyIndexRoute: AppCompanyIndexRoute,
}

const AppCompanyRouteWithChildren = AppCompanyRoute._addFileChildren(
  AppCompanyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  AppAdminRoute: AppAdminRoute,
  AppChallengesRoute: AppChallengesRouteWithChildren,
  AppCompanyRoute: AppCompanyRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppInternshipsRoute: AppInternshipsRoute,
  AppInterviewRoute: AppInterviewRoute,
  AppJobsRoute: AppJobsRoute,
  AppLeaderboardRoute: AppLeaderboardRoute,
  AppProfileRoute: AppProfileRoute,
  AppTasksRoute: AppTasksRoute,
  AppVideosRoute: AppVideosRoute,
  RegisterCandidateRoute: RegisterCandidateRoute,
  RegisterCompanyRoute: RegisterCompanyRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
